

load define_cst_options

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','C:\MATLABR11\work\kk.m', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[105 227 350 280], ...
	'Tag','Fig1', ...
    'MenuBar','none', ...
    'ToolBar','none');

hh1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[70 154.5 135 22.5], ...
	'String', 'Add links| Compute best global instances',...
	'Style','popupmenu', ...
	'Tag','PopupMenu1');




h1 = uicontrol('Parent',h0, ...
    'Callback', 'get_cst_options',...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[70 80 57 24.75], ...
   	'String','Ok', ...
	'Tag','Pushbutton1');

h1 = uicontrol('Parent',h0, ...
    'Callback', 'Close',...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[150 80 57 24.75], ...
    'String','Cancel', ...
	'Tag','Pushbutton1');

%if nargout > 0, fig = h0; end

