function fig = interface()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load interface

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','F:\MATLAB\work\interface.m', ...
    'Name','Possibilistic Network Propagation ', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[1 1 1024 729], ...
	'Tag','Fig1', ...
    'MenuBar','none', ...
    'ToolBar','none');

h1 = axes('Parent',h0, ...
	'CameraUpVector',[0 1 0], ...
	'CameraUpVectorMode','manual', ...
	'Color',[1 1 1], ...
	'ColorOrder',mat1, ...
	'Position',[0.1884765625 0.03292181069958847 0.7890625 0.9382716049382716], ...
	'Tag','zone', ...
	'XColor',[0 0 0], ...
	'XLim',[0 800], ...
	'XLimMode','manual', ...
	'XTickMode','manual', ...
	'YColor',[0 0 0], ...
	'YLim',[0 600], ...
	'YLimMode','manual', ...
	'YTickMode','manual', ...
	'ZColor',[0 0 0]);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[399.5043370508055 -7.027818448023368 9.160254037844386], ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-6.939281288723663 298.6822840409956 9.160254037844386], ...
	'Rotation',90, ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','baseline');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-192.3172242874845 617.5695461200585 9.160254037844386], ...
	'Tag','Axes1Text2', ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[399.5043370508055 606.1493411420205 9.160254037844386], ...
	'Tag','Axes1Text1', ...
	'VerticalAlignment','bottom');

set(get(h2,'Parent'),'Title',h2);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.847058823529412 0.815686274509804 0.784313725490196], ...
	'Callback','ajouter', ...
	'ListboxTop',0, ...
	'Position',[27 450 100 25], ...
	'String','Add node', ...
	'Tag','Pushbutton1');

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
  	'BackgroundColor',[0.847058823529412 0.815686274509804 0.784313725490196], ...
	'Callback','lien', ...
	'ListboxTop',0, ...
	'Position',[27 338.25 100 25], ...
	'String','Add link', ...
	'Tag','Pushbutton2');

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.847058823529412 0.815686274509804 0.784313725490196], ...
	'Callback','supprimer', ...
	'ListboxTop',0, ...
	'Position',[27 415.5 100 25], ...
	'String','Delete node', ...
	'Tag','Pushbutton3');

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.847058823529412 0.815686274509804 0.784313725490196], ...
	'Callback','supprlien',...
    'ListboxTop',0, ...
	'Position',[27 300 100 25], ...
    'String','Delete link', ...
	'Tag','Pushbutton4');

%----------------------------
h1 = uimenu('Parent',h0, ...
	'Label','&File', ...
   'Tag','uimenu1');

h2 = uimenu('Parent',h1, ...
   'Callback', 'new_PNT',...
	'Label','&New', ...
   'Tag','uimenu');

h2 = uimenu('Parent',h1, ...
   'Callback', 'open_PNT',...
	'Label','&Open...', ...
   'Tag','uimenu');

h2 = uimenu('Parent',h1, ...
   'Callback', 'save_PNT',...
	'Label','&Save as...', ...
   'Tag','uimenu');

h2 = uimenu('Parent',h1, ...
   'Callback', 'Close_PNT',...
	'Label','&Cancel', ...
   'Tag','uimenu');

%----------------------------

h1 = uimenu('Parent',h0, ...
	'Label','Network &Structure', ...
   'Tag','uimenu');
h2 = uimenu('Parent',h1, ...
	'Label','&Nodes', ...
   'Tag','uimenu');

h3 = uimenu('Parent',h2, ...
   'Callback','ajouter', ...
   'Label','&Add Node', ...
   'Tag','uimenu');
h3 = uimenu('Parent',h2, ...
   'Callback','supprimer', ...
   'Label','&Delete Node', ...
   'Tag','uimenu');
h2 = uimenu('Parent',h1, ...
	'Label','&Links', ...
   'Tag','uimenu');
h3 = uimenu('Parent',h2, ...
   	'Callback','lien', ...
	'Label','&Add Link', ...
   'Tag','uimenu');
h3 = uimenu('Parent',h2, ...
    'Callback','supprlien',...
	'Label','&Delete Link', ...
   'Tag','uimenu');

%----------------------------

h1 = uimenu('Parent',h0, ...
	'Label','Network &Quantification', ...
   'Tag','uimenu');

h2 = uimenu('Parent',h1, ...
   'Callback', 'define_distribution',...
   'Label','&Define Initial Distributions', ...
   'Tag','uimenu');

h2 = uimenu('Parent',h1, ...
   'Callback', 'define_evidence',...
   'Label','Define &Evidence', ...
   'Tag','uimenu');

h2 = uimenu('Parent',h1, ...
   'Callback', 'define_interest',...
   'Label','Define &Instance of Interest', ...
   'Tag','uimenu');

h2 = uimenu('Parent',h1, ...
   'Callback', 'reset_evidence_interest',...
   'Label','Reset Evidence and Instance of Interest', ...
   'Tag','uimenu');


%----------------------------

h1 = uimenu('Parent',h0, ...
   'Label','&Min-Based Inference', ...
   'Tag','uimenu');

h2 = uimenu('Parent',h1, ...
   'Callback', 'Pearl_propagation',...
   'Label','&Propagation in Polytrees', ...
   'Tag','uimenu');

h2 = uimenu('Parent',h1, ...
   'Callback', 'Jtree_propagation',...
   'Label','Propagation in &Junction Trees', ...
   'Tag','uimenu');

h2 = uimenu('Parent',h1, ...
   'Callback', 'define_consistency_options',...
   'Label','&Anytime Algorithm', ...
   'Tag','uimenu');

%----------------------------

h1 = uimenu('Parent',h0, ...
   'Label','&Product-based inference', ...
   'Tag','uimenu');

h2 = uimenu('Parent',h1, ...
   'Callback', 'prod_Pearl_propagation',...
   'Label','&Propagation in Polytrees', ...
   'Tag','uimenu');

h2 = uimenu('Parent',h1, ...
   'Callback', 'prod_Jtree_propagation',...
   'Label','&Propagation in &Junction Trees', ...
   'Tag','uimenu');

if nargout > 0, fig = h0; end
